#! /bin/bash

DB=phonebook.db

function clear() {
  [ -f "$DB" ] && rm "$DB"
}

function list() {
  if [ -f "$DB" ]; then
    cat "$DB"
  else
    echo Phonebook is empty
  fi
}

function new() {
  echo $* >>"$DB"
}

function remove() {
  echo REMOVE $*
  [ -f "$DB" ] && sed -i "/$*/d" "$DB"
}

function search() {
  [ -f "$DB" ] && grep "$*" "$DB"  
}

case $1 in
  clear) clear  ;;
  list)  list   ;;
  new)   shift; new $* ;;
  remove) shift; remove $* ;;
  *)     shift; search $* ;;
esac
